apiVersion: v1
kind: Pod
metadata:
  name: storage
  labels:
    podName: nginx-01
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
  containers:
    - name: debug
      image: rkalluru/learnk8s:rhel9-bare
      volumeMounts:
        - name: html
          mountPath: /mnt
  volumes:
    - name: html
      emptyDir: {}
