apiVersion: v1
kind: Pod
metadata:
  name: init-container
  labels:
    podName: nginx-01
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
  volumes:
    - name: html
      emptyDir: {}
